language: dart
dist: precise
dart:
  - 1.24.2

with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - ./tool/setup_dartium.sh
  - export PATH=$PATH":$PWD"
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub serve --port=59925 test &
  - sleep 3s
  - pub run test --concurrency=4 -p content-shell --reporter=expanded --pub-serve=59925 test/unit/generated_runner_test.dart
  - pub run dart_dev coverage --no-html
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
