language: dart
dist: precise
dart:
  - 1.24.2

with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - ./tool/setup_dartium.sh
  - export PATH=$PATH":$PWD"
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - pub run build_runner build
  - pub run dart_dev format --check
  # The analysis server can resolve elements from .dart_tool/build/, whereas the
  # dartanalyzer cli cannot (yet). For this reason, tuneup is used because it
  # leverages the analysis server. The dartanalyzer issue is being tracked here:
  # https://github.com/dart-lang/sdk/issues/34098
  - pub global activate tuneup
  - pub global run tuneup check --ignore-infos
  - pub run build_runner test -- --reporter=expanded
  # dart_dev coverage is unsupported on Dart 2 for the time being.
  # Long term, the hope is that coverage will be handled by the test package:
  # https://github.com/dart-lang/test/issues/36
  # - pub run dart_dev coverage --no-html
  # - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
