targets:
  $default:
    builders:
      build_web_compilers|ddc:
        generate_for:
          include:
            - "lib/**"
            - "test/**"
            - "web/**"
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        release_options:
          compiler: dart2js
          dart2js_args:
            - -O3

# Global options necessary to make sourcemaps work with dart2js
global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
  build_web_compilers|dart2js_archive_extractor:
    release_options:
      filter_outputs: false
