name: todo_dart_react
version: 2.0.0
description: Dart + React Todo List Example
homepage: https://github.com/leerob/dart-react-todo
author: Lee Robinson <lrobinson2011@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  over_react: ^2.0.0-alpha
  w_flux: ^2.10.1
  react: ^4.6.0

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  coverage: ^0.12.4
  dart_dev: ^2.0.3
  dart_style: ^1.0.8
  over_react_test: ^2.3.0
  test: ^1.5.3
