name: todo_dart_react
version: 2.0.0
description: Dart + React Todo List Example
homepage: https://github.com/leerob/dart-react-todo
author: Lee Robinson <me@leerob.io>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  over_react: ^2.5.2
  w_flux: ^2.10.3
  react: ^4.9.1

dev_dependencies:
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.4.0
  dart_dev: ^2.2.0
  dart_style: ^1.2.7
  over_react_test: ^2.5.1
  test: ^1.6.10
