name: todo_dart_react
version: 0.0.1
description: Dart + React Todo List Example
homepage: https://github.com/leerob/dart-react-todo
author: Lee Robinson <lee.robinson@workiva.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  w_flux: ^2.9.4
  over_react: ^1.18.1
  react: ^3.6.0

dev_dependencies:
  test: ^0.12.28
  over_react_test: ^1.3.1
  dart_dev: ^1.8.1
  dart_style: ^1.0.8

transformers:
- over_react
- $dart2js
- test/pub_serve:
    $include: test/**.dart